<a href="https://colab.research.google.com/github/namozhdehi/DataScience/blob/main/Unit%203%3A%20Introduction%20to%20Python%20I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Hello World**

In [ ]:
print('Hello World')
print("Hello World")

Hello World
Hello World


In [ ]:
age = 20
price = 19.95
first_name = "Nahid"
in_online = False
print(age)

20


In [ ]:
name = input("What is your name? ")
print("Hello " + str(name))

What is your name? Nahid
Hello Nahid


In [ ]:
# Converting: int() , float() , str() , bool()
birth_year = input("Enter your birth year: ")
age = 2024 - int(birth_year)
print(age)

Enter your birth year: 1990
34


In [ ]:
first = input("First: ")
second = input("Second: ")
sum = first + second
print(sum)

First: 1
Second: 5
15


In [ ]:
first = input("First: ")
second = input("Second: ")
sum = int(first) + int(second)
print(sum)

First: 1
Second: 5
6


In [ ]:
first = input("First: ")
second = input("Second: ")
sum = float(first) + float(second)
# print("Sum: " + sum) -- Error str + float
print("Sum: " + str(sum))

First: 1
Second: 5
Sum: 6.0


In [ ]:
first = float(input("First: "))
second = float(input("Second: "))
sum = first + second
print("Sum: " + str(sum))

First: 1
Second: 5
Sum: 6.0


In [ ]:
course = 'Python for beginners'
print(course.upper())
print(course)

PYTHON FOR BEGINNERS
Python for beginners


In [ ]:
course = 'Python for beginners'
print(course.find('y')) # index of accurance of 'y' in the string
print(course.find('Y')) # Case sensitive

1
-1


In [ ]:
course = 'Python for beginners'
print(course.find('for')) # return the index of the word 'for'
print('for' in course)

7
True


In [ ]:
course = 'Python for beginners'
print(course.replace('for', '4'))
print(course.replace('x', '4')) # no changes since we don't have x in our string

Python 4 beginners
Python for beginners


In [ ]:
print(10 / 3) # return floating
print(10 // 3) # return int
print(10 % 3 ) # remainder
print(10 ** 3 ) # 10 to the power of 3

3.3333333333333335
3
1
1000


In [ ]:
x = 10
x = x + 3 # or x += 3 called augmented assignment operator
print(x)

13


In [ ]:
x = 10 + 3 * 2
print(x)

16


In [ ]:
x = 3 >= 2
x = 3 <= 2
x = 3 != 2
x = 3 == 2
print(x)

False


In [ ]:
price = 25
print(price > 10 and price < 30) # and , or
print(price > 10)
print(not price > 10)

True
True
False


In [ ]:
temperature = 25
if temperature > 30:
  print("It's a hot day")
  print("Drink plenty of water")
elif temperature > 20:  # between (20, 30]
  print("It's a nice day")
elif temperature > 10: # (10, 20]
  print("It's chili")
else:
  print("It's cold")

print("Done")

It's a nice day
Done


In [ ]:
weight = float(input("Weight: "))
unit = input("(K)g or (L)bs:")
if unit.upper() == "K":
  converted = weight / 0.45
  print("Weight in Lbs: " + str(converted))
else:
  converted = weight * 0.45
  print("Weight in Kgs: " + str(converted))

Weight: 65
(K)g or (L)bs:k
Weight in Lbs: 144.44444444444443


In [ ]:
i = 1
while i <= 1_0: # means 10 eg: 1_000 means 1000
  print(i)
  i += 1

1
2
3
4
5
6
7
8
9
10


In [ ]:
i = 1
while i <= 3:
  print(i * '*')
  i += 1

*
**
***


In [ ]:
names = ["Jon", "Bob", "Mary"]
print(names[0])
print(names[-1]) # from the end of list

Jon
Mary


In [ ]:
names[0] = "John"
print(names)
print(names[0:2]) # doesn't consider 2

['John', 'Bob', 'Mary']
['John', 'Bob']


**List**

In [ ]:
numbers = [1, 2, 3, 4, 5]
numbers.append(6)
print(numbers)

numbers.insert(0, -5)
print(numbers)

numbers.remove(3)
print(numbers)

numbers.clear()
print(numbers)

[1, 2, 3, 4, 5, 6]
[-5, 1, 2, 3, 4, 5, 6]
[-5, 1, 2, 4, 5, 6]
[]


In [ ]:
numbers = [1, 2, 3, 4, 5]
print(1 in numbers)

print(len(numbers))

True
5


In [ ]:
# for
numbers = [1, 2, 3]
for item in numbers:
  print(item)

# while
numbers = [1, 2, 3]
i = 0
while i < len(numbers):
  print(numbers[i])
  i += 1

1
2
3


In [ ]:
numbers = range(3)
print(numbers)

range(0, 3)


In [ ]:
numbers = range(3)
for number in numbers:
  print(number)

0
1
2


In [ ]:
numbers = range(5, 10)
for number in numbers:
  print(number)

5
6
7
8
9


In [ ]:
numbers = range(5, 10, 2)
for number in numbers:
  print(number)

5
7
9


In [ ]:
for number in range(5):
  print(number)

0
1
2
3
4


**Tuple**

In [ ]:
numbers = (1, 2, 3)
numbers[0] = 5

TypeError: 'tuple' object does not support item assignment

In [ ]:
numbers = (1, 2, 3, 3)
numbers.count(3) # number of occurrences of value

2

In [ ]:
numbers = (1, 2, 3, 3)
numbers.index(2) # returns the index of the first occurrences of given element

1

 **Python Lists**

In [ ]:
example = [128, True, "Alpha", 1.732, [64, False], 128]
example[4]

[64, False]

In [ ]:
# concatination of 2 lists
numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
numbers + letters

[1, 2, 3, 'a', 'b', 'c']

In [ ]:
dir(numbers)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
numbers = [1, 2, 3]
print(numbers.reverse())

None


In [ ]:
a = [3, 10, -1]
print(a)

[3, 10, -1]


In [ ]:
a.append(1)
print(a)

[3, 10, -1, 1]


In [ ]:
a.append("hello")
print(a)

[3, 10, -1, 1, 'hello']


In [ ]:
a.append([1,2])
print(a)

[3, 10, -1, 1, 'hello', [1, 2]]


In [ ]:
a.pop()
print(a)

[3, 10, -1, 1, 'hello']


In [ ]:
a[0]

3

In [ ]:
a[0] = 100
print(a)

[100, 10, -1, 1, 'hello']


In [ ]:
# swap a[0] and a[2]
b = ["banana", "apple", "microsoft"]
swap = b[0]
b[0] = b[2]
b[2] = swap

print(b)

# another way:
b = ["banana", "apple", "microsoft"]
b[0] , b[2] = b[2] , b[0]
print(b)

['microsoft', 'apple', 'banana']
['microsoft', 'apple', 'banana']


## **Functions and Packages**

In [ ]:
def function1():
  print("ah")
  print("ahh 2")
print("this is outside the function")

this is outside the function


In [ ]:
function1()

ah
ahh 2


In [ ]:
# a mapping
# input or an argument
def function2(x):
  return 2*x

a = function2(3)
# return value or output

print(a)

6


In [ ]:
d = function2()

TypeError: function2() missing 1 required positional argument: 'x'

In [ ]:
def function3(x, y):
  return x + y

e = function3(1, 2)
print(e)

3


In [ ]:
def function4(x):
  print(x)
  print("still in this function")
  return 3 * x

f = function4(4)

4
still in this function


In [ ]:
print(f)

12


In [ ]:
def function5(some_argument):
  print(some_argument)
  print("weee")

function5(4)

4
weee


In [ ]:
#BMI calculater
name1 = "YK"
height_m1 = 2
weight_kg1 = 90

name2 = "YK's siter"
height_m2 = 1.8
weight_kg2 = 70

name3 = "YK's brother"
height_m3 = 2.5
weight_kg3 = 160

def bmi_calculator(name, height_m, weight_kg):
  bmi = weight_kg / (height_m ** 2)
  print("bmi: ")
  print(bmi)
  if bmi < 25:
    return name + " is not overweight"
  else:
    return name + " is overweight"

In [ ]:
result1 = bmi_calculator(name1, height_m1, weight_kg1)
result2 = bmi_calculator(name2, height_m2, weight_kg2)
result3 = bmi_calculator(name3, height_m3, weight_kg3)

print(result1)
print(result2)
print(result3)

bmi: 
22.5
bmi: 
21.604938271604937
bmi: 
25.6
YK is not overweight
YK's siter is not overweight
YK's brother is overweight


**Function**

In [ ]:
def f():
  pass # skip this line
f()

In [ ]:
f # returns memory address

<function __main__.f()>

In [ ]:
dir() # list of functions (f is added)

['In',
 'Out',
 '_',
 '_13',
 '_14',
 '_15',
 '_16',
 '_18',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'f',
 'get_ipython',
 'i',
 'number',
 'numbers',
 'quit']

In [ ]:
def ping(): # 0 arguments
  return "Ping!"
ping()

'Ping!'

In [ ]:
def ping(): # 0 arguments
  return "Ping!"
x = ping()
print(x)

Ping!


In [ ]:
dir() # ping and x are added

['In',
 'Out',
 '_',
 '_13',
 '_14',
 '_15',
 '_16',
 '_18',
 '_19',
 '_20',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'f',
 'get_ipython',
 'i',
 'number',
 'numbers',
 'ping',
 'quit',
 'x']

In [ ]:
#V = 4/3 pi r^3
import math


def volume(r):
  """ Returns the volume of a sphere with radius r.""" # doc string for ducumentation
  v = (4.0 / 3.0) * math.pi * r**3
  return v

volume(2)
volume() # Error

33.510321638291124

In [ ]:
# A = 1/2 b.h

def triangle_area(b, h):
  """ Returns the area of a triangle with base b and height h."""
  return 0.5 * b * h

triangle_area(3, 6)

9.0

In [ ]:
# Keyword Argument

def cm(feet = 0, inches = 0): # keyword arguments , defualt arguments
  """Converts a length from feet and inches to centimeters. """
  inches_to_cm = inches * 2.54
  feet_to_cm = feet * 12 * 2.54
  return inches_to_cm + feet_to_cm

cm(feet = 5)
cm(inches = 70)
cm(feet = 5, inches = 8)
cm(inches = 8 , feet = 5)

172.72

In [ ]:
def g(x=0, y):
  return x + y

SyntaxError: non-default argument follows default argument (<ipython-input-29-b1c4461a698f>, line 1)

In [ ]:
def g(y, x=0): # default argument first: no error
  return x + y

g(5)
g(7, x = 3)

5

**NumPy**

In [ ]:
stuff = [1, 'apple', f00]
print(stuff[1])

NameError: name 'f00' is not defined

In [ ]:
# Array are sequence of types and behave very much like lists, except that the type objects stored in them is constrained. The type is specified at object certain time
# class arry.arry(typecode[, initializer])
import array
numbers = array.array('i', [1, 2, 3, 4, 5])
print(numbers)

array('i', [1, 2, 3, 4, 5])


In [ ]:
import array
numbers = array.array('i', [1, 2, 3, 4, 5])
for number in numbers:
  print(number)

1
2
3
4
5


In [ ]:
import array
numbers = array.array('i', [1, 2, 3, 4, 5])
numbers.append(6)
numbers

array('i', [1, 2, 3, 4, 5, 6])

In [ ]:
import array
numbers = array.array('i', [1, 2, 3, 4, 5]) # i: integer
numbers.append("apple")
numbers

TypeError: 'str' object cannot be interpreted as an integer

**NumPy**

 **1.Create**

In [ ]:
!pip install numpy

In [ ]:
# Create array
import numpy as np

data = np.random.rand(2, 3, 4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

print(data)

print("------")
print(zeroes)

print("------")
print(full)

print("------")
print(ones)

[[[0.85794741 0.31721948 0.21168709 0.02746633]
  [0.31303495 0.53644661 0.62765595 0.09743853]
  [0.41571366 0.53529699 0.817797   0.17515529]]

 [[0.65595781 0.82006401 0.97935062 0.08244253]
  [0.48422181 0.15836401 0.94600535 0.72935253]
  [0.45031799 0.13234355 0.51109739 0.07891525]]]
------
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
------
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]
------
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [ ]:
arr = np.array([[1, 2, 3,4], [1, 2, 3, 4]])

type(arr)

numpy.ndarray

**2. Read**

In [ ]:
import numpy as np

data = np.random.rand(2, 3, 4)

shape = data.shape
size = data.size
types = data.dtype

print(shape)
print(size)
print(types)

(2, 3, 4)
24
float64


In [ ]:
# slicing
arr = data[0]
slicer = data[0:2]

slicer2 = data[0][0:2]

reverse = data[-1]
singleval = data[0][0]

print("------")
print(arr)
print("\nslicer------")
print(slicer)
print("\nslicer2------")
print(slicer2)
print("------")
print(reverse)
print("------")
print(singleval)

------
[[0.23696676 0.89788156 0.76221038 0.17478382]
 [0.64835719 0.00891005 0.85542366 0.1398875 ]
 [0.58310973 0.03549418 0.72444734 0.97526357]]

slicer------
[[[0.23696676 0.89788156 0.76221038 0.17478382]
  [0.64835719 0.00891005 0.85542366 0.1398875 ]
  [0.58310973 0.03549418 0.72444734 0.97526357]]

 [[0.05037326 0.23361    0.47030662 0.70842716]
  [0.16948422 0.95434816 0.6599673  0.28001484]
  [0.67447875 0.05306198 0.31256626 0.61034538]]]

slicer2------
[[0.23696676 0.89788156 0.76221038 0.17478382]
 [0.64835719 0.00891005 0.85542366 0.1398875 ]]
------
[[0.05037326 0.23361    0.47030662 0.70842716]
 [0.16948422 0.95434816 0.6599673  0.28001484]
 [0.67447875 0.05306198 0.31256626 0.61034538]]
------
[0.23696676 0.89788156 0.76221038 0.17478382]


 **3.Update**

In [ ]:
import numpy as np
list1 = np.random.rand(10)
list2 = np.random.rand(10)

print(list1)
print("------")
print(list2)

[0.6603916  0.17975339 0.2298381  0.80383295 0.33313516 0.20987973
 0.45733524 0.43216204 0.23518503 0.61959958]
------
[0.15321177 0.32263541 0.81612871 0.01334413 0.73484016 0.25855264
 0.8157818  0.57915772 0.54273212 0.42766984]


In [ ]:
# basic math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

print("add----")
print(add)
print("sub----")
print(sub)
print("div----")
print(div)
print("mult----")
print(mult)
print("dot----") # multiply 2 arry and add products
print(dot)

add----
[0.81360337 0.5023888  1.0459668  0.81717708 1.06797532 0.46843237
 1.27311703 1.01131976 0.77791716 1.04726942]
sub----
[ 0.50717983 -0.14288202 -0.58629061  0.79048882 -0.401705   -0.04867291
 -0.35844656 -0.14699568 -0.30754709  0.19192974]
div----
[ 4.31031889  0.55714092  0.28161991 60.23868023  0.4533437   0.81174854
  0.56060976  0.74619059  0.43333539  1.44878016]
mult----
[0.10117977 0.05799481 0.18757747 0.01072645 0.24480109 0.05426496
 0.37308576 0.25028998 0.12764247 0.26498405]
dot----
1.6725468223061801


In [ ]:
#stat function
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp(2,3)
min = np.min(list1)
exp = np.max(list1)

In [ ]:
data.sort()
data

array([[[0.17478382, 0.23696676, 0.76221038, 0.89788156],
        [0.00891005, 0.1398875 , 0.64835719, 0.85542366],
        [0.03549418, 0.58310973, 0.72444734, 0.97526357]],

       [[0.05037326, 0.23361   , 0.47030662, 0.70842716],
        [0.16948422, 0.28001484, 0.6599673 , 0.95434816],
        [0.05306198, 0.31256626, 0.61034538, 0.67447875]]])

In [ ]:
print(data.shape)

(2, 3, 4)


In [ ]:
print(data)
print('------')
data = data.reshape((2,2,-1))
print(data.shape)
print(data)

[[[0.17478382 0.23696676 0.76221038 0.89788156 0.00891005 0.1398875 ]
  [0.64835719 0.85542366 0.03549418 0.58310973 0.72444734 0.97526357]]

 [[0.05037326 0.23361    0.47030662 0.70842716 0.16948422 0.28001484]
  [0.6599673  0.95434816 0.05306198 0.31256626 0.61034538 0.67447875]]]
------
(2, 2, 6)
[[[0.17478382 0.23696676 0.76221038 0.89788156 0.00891005 0.1398875 ]
  [0.64835719 0.85542366 0.03549418 0.58310973 0.72444734 0.97526357]]

 [[0.05037326 0.23361    0.47030662 0.70842716 0.16948422 0.28001484]
  [0.6599673  0.95434816 0.05306198 0.31256626 0.61034538 0.67447875]]]


In [ ]:
zeros = np.zeros((8))
print(zeros)
zeros = np.append(zeros, [3,4])
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [ ]:
zeros = np.insert(zeros, 2, 1) # insert 1 into position 2
print(zeros)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


**4. Delete**

In [ ]:
data

array([[[0.17478382, 0.23696676, 0.76221038, 0.89788156, 0.00891005,
         0.1398875 ],
        [0.64835719, 0.85542366, 0.03549418, 0.58310973, 0.72444734,
         0.97526357]],

       [[0.05037326, 0.23361   , 0.47030662, 0.70842716, 0.16948422,
         0.28001484],
        [0.6599673 , 0.95434816, 0.05306198, 0.31256626, 0.61034538,
         0.67447875]]])

In [ ]:
np.delete(data, 0, axis=1) # axis = 1 : delete row

array([[[0.64835719, 0.85542366, 0.03549418, 0.58310973, 0.72444734,
         0.97526357]],

       [[0.6599673 , 0.95434816, 0.05306198, 0.31256626, 0.61034538,
         0.67447875]]])

In [ ]:
np.save("new array", data)

**Multidimensional Arrays**

In [ ]:
!pip install numpy
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [ ]:
# zero dimensional array
zero_dim = np.array(123456)
print(zero_dim)

# one dimensional array
one_dim = np.array([1, 2, 3])
print(one_dim)

# two dimensional array
two_dim = np.array([[1, 2, 3] , [4, 5, 6]])
print(two_dim)

# three dimensional array
three_dim = np.array([[[1, 2, 3] , [4, 5, 6]], [[7, 8, 9] , [10, 11, 12]]])
print(three_dim)

123456
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# fininf the dimension of a given arry
print(zero_dim.ndim)
print(one_dim.ndim)
print(two_dim.ndim)
print(three_dim.ndim)

0
1
2
3


In [ ]:
# Given an array any dimension you want
new_array = np.array(17, ndmin = 5)
print(new_array)

new_array = np.array([1, 2], ndmin = 5)
print(new_array)

[[[[[17]]]]]
[[[[[1 2]]]]]


**Python Simplified: More on NumPy Arrays**

In [ ]:
!pip install numpy
import numpy as np

my_array = np.arange(8)
print(my_array)
print(type(my_array))

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
my_array = np.arange(1, 8)
print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [ ]:
my_array = np.arange(1, 8, 2) # start, stop, step
print(my_array)
print(type(my_array))

[1 3 5 7]
<class 'numpy.ndarray'>


In [ ]:
my_array = np.arange(1, 8, 0.5) # start, stop, step
print(my_array)
print(type(my_array))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
<class 'numpy.ndarray'>


In [ ]:
# arrays from lists
from_list = np.array([1, 2, 3])
print(from_list)

print(type(from_list[0]))

[1 2 3]
<class 'numpy.int64'>


In [ ]:
from_list = np.array([1, 2, 3], dtype = np.int8)
print(from_list)

print(type(from_list[0]))

[1 2 3]
<class 'numpy.int8'>


In [ ]:
!pip install numpy
import numpy as np

# 2D arrays
from_list = np.array([[1, 2, 3], [4,5,6]], dtype = np.int8)
print(from_list)

[[1 2 3]
 [4 5 6]]


In [ ]:
my_array = np.arange(1, 8)
print(my_array)
print(type(my_array))

print('1D array', my_array)
print(my_array.shape, '\n')

from_list = np.array([[1, 2, 3], [4,5,6]], dtype = np.int8)
array_2d = np.array((np.arange(0,8, 2), np.arange(1,8,2)))
print('2D array',array_2d)
print(array_2d.shape)


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1D array [1 2 3 4 5 6 7]
(7,) 

2D array [[0 2 4 6]
 [1 3 5 7]]
(2, 4)


In [ ]:
array_2d = np.array((np.arange(0,8, 2), np.arange(1,8,2)))
print('2D array',array_2d)
print(array_2d.shape, '\n')

array_2d = array_2d.reshape((4, 2))
print(array_2d)

2D array [[0 2 4 6]
 [1 3 5 7]]
(2, 4) 

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [ ]:
array_2d = np.array((np.arange(0,8, 2), np.arange(1,8,2)))

array_2d = array_2d.reshape((2, 1, 4))
print(array_2d)
print('2D array',array_2d.shape)

[[[0 2 4 6]]

 [[1 3 5 7]]]
2D array (2, 1, 4)


In [ ]:
# empty array
empty_array = np.zeros((2,2))
print(empty_array, '\n')

one_array = np.ones((2,2))
print(one_array)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]]


In [ ]:
# empty returns random values
empty_array = np.empty((2,2))
print(empty_array, '\n')

empty_array = np.empty((2, 2,2))
print(empty_array, '\n')

[[1. 1.]
 [1. 1.]] 

[[[0.0e+000 9.9e-324]
  [2.0e-323 3.0e-323]]

 [[4.9e-324 1.5e-323]
  [2.5e-323 3.5e-323]]] 



In [ ]:
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
eye_array = np.eye(3, k=-1)
print(eye_array)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
eye_array = np.eye(3, k=1)
print(eye_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
eye_array = np.eye(3, k=1)
eye_array[eye_array == 0] = 2
print(eye_array)

[[2. 1. 2.]
 [2. 2. 1.]
 [2. 2. 2.]]


In [ ]:
eye_array[eye_array < 2] = 9
print(eye_array)

[[2. 9. 2.]
 [2. 2. 9.]
 [2. 2. 2.]]


In [ ]:
eye_array[0] = 3
print(eye_array)

[[3. 3. 3.]
 [2. 2. 9.]
 [2. 2. 2.]]


In [ ]:
eye_array[:2] = 3
print(eye_array)

[[3. 3. 3.]
 [3. 3. 3.]
 [2. 2. 2.]]


In [ ]:
eye_array[: ,0] = 4
print(eye_array)

[[4. 3. 3.]
 [4. 3. 3.]
 [4. 3. 3.]]


In [ ]:
eye_array[: , -1] = 4
print(eye_array)

[[4. 3. 4.]
 [4. 3. 4.]
 [4. 3. 4.]]


In [ ]:
sorted_array = np.sort(eye_array)
print(sorted_array)

[[3. 4. 4.]
 [3. 4. 4.]
 [3. 4. 4.]]


In [ ]:
# sort by column 0:column -1:rows
sorted_array = np.sort(eye_array, axis = 0)
print(sorted_array)

[[4. 3. 4.]
 [4. 3. 4.]
 [4. 3. 4.]]


In [ ]:
# defualt sort is quicksort and we can change it to other kind of sort (mergesort, heapsort)
sorted_array = np.sort(eye_array, axis = 0, kind = "mergesort")
print(sorted_array)

[[4. 3. 4.]
 [4. 3. 4.]
 [4. 3. 4.]]


In [ ]:
# copy arrays
my_view = sorted_array.view()
my_copy = sorted_array.copy()

# both my_view and sorted_array change
my_view[:] = 4
print(my_view, '\n')
print(sorted_array, '\n')


[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 



In [ ]:

# copy just change and sorted_array hasn't changed
my_copy[:] = 4
print(my_copy, '\n')
print(sorted_array, '\n')

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 



In [ ]:
my_view = my_view.reshape(3,3,1)
print(my_view, '\n')
print(sorted_array, '\n')

[[[4.]
  [4.]
  [4.]]

 [[4.]
  [4.]
  [4.]]

 [[4.]
  [4.]
  [4.]]] 

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] 



In [ ]:
import numpy as np
np_heights = np.array([[1.60,1.75],[1.56,1.70],[1.49,1.68]])
print(np.corrcoef(np_heights[:,0], np_heights[:,1]))

[[1.         0.92155064]
 [0.92155064 1.        ]]


In [ ]:
# optional arguments: q, r2
def function_1(p, r1 [, q][, r2])

In [ ]:
a = lambda x: x*2
for i in range(1,6):
    print(a(i))

2
4
6
8
10


In [ ]:
def outer_function():
    a = 5
    def inner_function():
        nonlocal a
        a = 10
        print("Inner function: ",a)
    inner_function()
    print("Outer function: ",a)

outer_function()

Inner function:  10
Outer function:  10


In [ ]:
def outer_function():
    a = 5
    def inner_function():
        a = 10
        print("Inner function: ",a)
    inner_function()
    print("Outer function: ",a)

outer_function()

Inner function:  10
Outer function:  5


In [ ]:
def func_return():
    a = 10
    return a

def no_return():
    a = 10

print(func_return())
print(no_return())

10
None


In [ ]:
# This example writes the text Hello world! to the file example.txt
with open('example.txt', 'w') as my_file:
    my_file.write('Hello world!')

In [ ]:
g = (2**x for x in range(100))
next(g)

1

In [ ]:
next(g)

2

In [ ]:
def generator():
    for i in range(6):
        yield i*i

g = generator()
for i in g:
    print(i)

0
1
4
9
16
25


In [ ]:
def a_void_function():
    a = 1
    b = 2
    c = a + b

x = a_void_function()
print(x)

None


In [ ]:
def improper_return_function(a):
    if (a % 2) == 0:
        return True

x = improper_return_function(3)
print(x)

None


In [ ]:
# The async and await keywords are provided by the asyncio library in Python. They are used to write concurrent code in Python.
import asyncio

async def main():
    print('Hello')
    await asyncio.sleep(1)
    print('world')

In [ ]:
#In the above program, the async keyword specifies that the function will be executed asynchronously.
asyncio.run(main())

RuntimeError: asyncio.run() cannot be called from a running event loop

In [ ]:
#break will end the smallest loop it is in and control flows to the statement immediately below the loop.

for i in range(1,11):
    if i == 5:
        break
    print(i)

1
2
3
4


In [ ]:
# continue causes to end the current iteration of the loop, but not the whole loop.
for i in range(1,11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [ ]:
def my_function(x):
    return x * 2

print(my_function(7))

14


In [ ]:
import numpy as np
np.multiply(2,1)

2

In [ ]:
x = ["a", "b", "c", "d"]
del(x[1])

In [ ]:
help(max)
#?max

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [ ]:
# Assuming 'full' is a list
full = [10, 65, 22, 11, 3, 78, 90]  # Example list

# Sort 'full' in descending order
full_sorted = sorted(full, reverse=True)

In [ ]:
# Import the numpy package as np
import numpy as np

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(np_baseball)

# **pow() takes three arguments: base, exp, and mod. base and exp are required arguments, mod is an optional argument.**

# **A list can have items from a mixture of datatypes, while an array must have items of all the same datatype.**